replicaCount: 2

image:
  repository: ghcr.io/tolgayld/buzzup/post-ms
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8004
  targetPort: 8004

imagePullSecrets:
  - name: github-registry-secret
