replicaCount: 2

image:
  repository: ghcr.io/tolgayld/buzzup/story-ms
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8006
  targetPort: 8006

imagePullSecrets:
  - name: github-registry-secret
