replicaCount: 1

image:
  repository: ghcr.io/tolgayld/buzzup/report-ms
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8005
  targetPort: 8005

imagePullSecrets:
  - name: github-registry-secret
