include: package:flutter_lints/flutter.yaml

linter:
  rules:
    public_member_api_docs: false
    require_trailing_commas: true
    prefer_final_locals: true
    sort_constructors_first: true
    prefer_final_in_for_each: true
    use_super_parameters: true
    implicit_call_tearoffs: true
    unnecessary_lambdas: true

analyzer:
  exclude:
    - "**.g.dart"
    - "**.freezed.dart"
    - "**.mapper.dart"
    - "**.gql.g.dart"
    - "**.gql.dart"
    - "lib/core/utils/graphql/**"
    - "lib/core/localization/**"
