synthetic-package: false

nullable-getter: false
arb-dir: lib/core/lang
template-arb-file: app_de.arb
output-localization-file: localizations.dart
output-dir: lib/core/localization
output-class: L10n
untranslated-messages-file: lib/core/lang/untranslated/untranslated.arb
