replicaCount: 2

image:
  repository: ghcr.io/tolgayld/buzzup/auth-ms
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8001
  targetPort: 8001

imagePullSecrets:
  - name: github-registry-secret
