replicaCount: 1

image:
  repository: ghcr.io/tolgayld/buzzup/gateway
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

imagePullSecrets:
  - name: github-registry-secret
