replicaCount: 1

image:
  repository: ghcr.io/tolgayld/buzzup/comment-ms
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8003
  targetPort: 8003

imagePullSecrets:
  - name: github-registry-secret
